/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Scopes;

import java.awt.CardLayout;

/**
 *
 * @author Administrator
 */
public class TopFrame extends javax.swing.JFrame {

   /**
    * Creates new form TopFrame
    */
   public TopFrame() {
      initComponents();
      CardLayout cl = (CardLayout)(this.catOneCardPanel.getLayout());
      cl.show(this.catOneCardPanel, "Blank");
      this.validate();      
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      pnlCategoriesButtons = new javax.swing.JPanel();
      btnCategoryOne = new javax.swing.JButton();
      btnCategoryTwo = new javax.swing.JButton();
      btnCategoryThree = new javax.swing.JButton();
      cardPanel = new javax.swing.JPanel();
      catBlankPanel = new javax.swing.JPanel();
      catOnePanel = new javax.swing.JPanel();
      lblCatOnePanel = new javax.swing.JLabel();
      catOneCardPanel = new javax.swing.JPanel();
      catOneBlankPanel = new javax.swing.JPanel();
      catOneCardPanelView = new javax.swing.JPanel();
      jLabel2 = new javax.swing.JLabel();
      catOneCardPanelReview = new javax.swing.JPanel();
      jLabel3 = new javax.swing.JLabel();
      catOneCardPanelUpdate = new javax.swing.JPanel();
      jLabel4 = new javax.swing.JLabel();
      catOneButtonPanel = new javax.swing.JPanel();
      btnCatOneView = new javax.swing.JButton();
      btnCatOneReview = new javax.swing.JButton();
      btnCatOneUpdate = new javax.swing.JButton();
      catTwoPanel = new javax.swing.JPanel();
      catThreePanel = new javax.swing.JPanel();
      catFourPanel = new javax.swing.JPanel();
      lblStart = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      btnCategoryOne.setText(" Category One");
      btnCategoryOne.setMaximumSize(new java.awt.Dimension(45, 15));
      btnCategoryOne.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCategoryOneActionPerformed(evt);
         }
      });
      pnlCategoriesButtons.add(btnCategoryOne);

      btnCategoryTwo.setText("Category Two");
      btnCategoryTwo.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCategoryTwoActionPerformed(evt);
         }
      });
      pnlCategoriesButtons.add(btnCategoryTwo);

      btnCategoryThree.setText("CategoryThree");
      btnCategoryThree.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCategoryThreeActionPerformed(evt);
         }
      });
      pnlCategoriesButtons.add(btnCategoryThree);

      getContentPane().add(pnlCategoriesButtons, java.awt.BorderLayout.NORTH);

      cardPanel.setLayout(new java.awt.CardLayout());

      javax.swing.GroupLayout catBlankPanelLayout = new javax.swing.GroupLayout(catBlankPanel);
      catBlankPanel.setLayout(catBlankPanelLayout);
      catBlankPanelLayout.setHorizontalGroup(
         catBlankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 719, Short.MAX_VALUE)
      );
      catBlankPanelLayout.setVerticalGroup(
         catBlankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 325, Short.MAX_VALUE)
      );

      cardPanel.add(catBlankPanel, "card5");

      catOnePanel.setBackground(new java.awt.Color(220, 220, 100));
      catOnePanel.setLayout(new java.awt.BorderLayout());

      lblCatOnePanel.setBackground(new java.awt.Color(255, 255, 255));
      lblCatOnePanel.setForeground(new java.awt.Color(0, 153, 204));
      lblCatOnePanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      lblCatOnePanel.setText("C A T E G O R Y   O N E");
      lblCatOnePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 124, 225), 3));
      catOnePanel.add(lblCatOnePanel, java.awt.BorderLayout.NORTH);

      catOneCardPanel.setLayout(new java.awt.CardLayout());

      javax.swing.GroupLayout catOneBlankPanelLayout = new javax.swing.GroupLayout(catOneBlankPanel);
      catOneBlankPanel.setLayout(catOneBlankPanelLayout);
      catOneBlankPanelLayout.setHorizontalGroup(
         catOneBlankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 719, Short.MAX_VALUE)
      );
      catOneBlankPanelLayout.setVerticalGroup(
         catOneBlankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 272, Short.MAX_VALUE)
      );

      catOneCardPanel.add(catOneBlankPanel, "Blank");

      jLabel2.setText("View");

      javax.swing.GroupLayout catOneCardPanelViewLayout = new javax.swing.GroupLayout(catOneCardPanelView);
      catOneCardPanelView.setLayout(catOneCardPanelViewLayout);
      catOneCardPanelViewLayout.setHorizontalGroup(
         catOneCardPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(catOneCardPanelViewLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel2)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      catOneCardPanelViewLayout.setVerticalGroup(
         catOneCardPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(catOneCardPanelViewLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel2)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      catOneCardPanel.add(catOneCardPanelView, "View");

      jLabel3.setText("Review");

      javax.swing.GroupLayout catOneCardPanelReviewLayout = new javax.swing.GroupLayout(catOneCardPanelReview);
      catOneCardPanelReview.setLayout(catOneCardPanelReviewLayout);
      catOneCardPanelReviewLayout.setHorizontalGroup(
         catOneCardPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(catOneCardPanelReviewLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel3)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      catOneCardPanelReviewLayout.setVerticalGroup(
         catOneCardPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(catOneCardPanelReviewLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel3)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      catOneCardPanel.add(catOneCardPanelReview, "Review");

      jLabel4.setText("Update");

      javax.swing.GroupLayout catOneCardPanelUpdateLayout = new javax.swing.GroupLayout(catOneCardPanelUpdate);
      catOneCardPanelUpdate.setLayout(catOneCardPanelUpdateLayout);
      catOneCardPanelUpdateLayout.setHorizontalGroup(
         catOneCardPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(catOneCardPanelUpdateLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel4)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      catOneCardPanelUpdateLayout.setVerticalGroup(
         catOneCardPanelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(catOneCardPanelUpdateLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel4)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      catOneCardPanel.add(catOneCardPanelUpdate, "Update");

      catOnePanel.add(catOneCardPanel, java.awt.BorderLayout.CENTER);

      catOneButtonPanel.setBackground(new java.awt.Color(51, 51, 255));

      btnCatOneView.setText("View");
      btnCatOneView.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCatOneViewActionPerformed(evt);
         }
      });
      catOneButtonPanel.add(btnCatOneView);

      btnCatOneReview.setText("Review");
      btnCatOneReview.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCatOneReviewActionPerformed(evt);
         }
      });
      catOneButtonPanel.add(btnCatOneReview);

      btnCatOneUpdate.setText("Update");
      btnCatOneUpdate.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCatOneUpdateActionPerformed(evt);
         }
      });
      catOneButtonPanel.add(btnCatOneUpdate);

      catOnePanel.add(catOneButtonPanel, java.awt.BorderLayout.SOUTH);

      cardPanel.add(catOnePanel, "catOneCard");

      catTwoPanel.setBackground(new java.awt.Color(100, 220, 220));

      javax.swing.GroupLayout catTwoPanelLayout = new javax.swing.GroupLayout(catTwoPanel);
      catTwoPanel.setLayout(catTwoPanelLayout);
      catTwoPanelLayout.setHorizontalGroup(
         catTwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 719, Short.MAX_VALUE)
      );
      catTwoPanelLayout.setVerticalGroup(
         catTwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 325, Short.MAX_VALUE)
      );

      cardPanel.add(catTwoPanel, "catTwoCard");

      catThreePanel.setBackground(new java.awt.Color(220, 100, 220));

      javax.swing.GroupLayout catThreePanelLayout = new javax.swing.GroupLayout(catThreePanel);
      catThreePanel.setLayout(catThreePanelLayout);
      catThreePanelLayout.setHorizontalGroup(
         catThreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 719, Short.MAX_VALUE)
      );
      catThreePanelLayout.setVerticalGroup(
         catThreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 325, Short.MAX_VALUE)
      );

      cardPanel.add(catThreePanel, "catThreeCard");

      getContentPane().add(cardPanel, java.awt.BorderLayout.CENTER);

      catFourPanel.setBackground(new java.awt.Color(0, 204, 255));

      lblStart.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
      lblStart.setText("W E L C O M E");
      lblStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      catFourPanel.add(lblStart);

      getContentPane().add(catFourPanel, java.awt.BorderLayout.SOUTH);

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btnCategoryOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryOneActionPerformed
      CardLayout cl = (CardLayout)(this.cardPanel.getLayout());
      cl.show(this.cardPanel, "catOneCard");
      // TODO add your handling code here:
   }//GEN-LAST:event_btnCategoryOneActionPerformed

   private void btnCatOneViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatOneViewActionPerformed
      // TODO add your handling code here:
      CardLayout cl = (CardLayout)(this.catOneCardPanel.getLayout());
      cl.show(this.catOneCardPanel, "View"); 
   }//GEN-LAST:event_btnCatOneViewActionPerformed

   private void btnCategoryTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryTwoActionPerformed
      CardLayout cl = (CardLayout)(this.cardPanel.getLayout());
      cl.show(this.cardPanel, "catTwoCard");      // TODO add your handling code here:
   }//GEN-LAST:event_btnCategoryTwoActionPerformed

   private void btnCategoryThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryThreeActionPerformed
      CardLayout cl = (CardLayout)(this.cardPanel.getLayout());
      cl.show(this.cardPanel, "catThreeCard");      // TODO add your handling code here:
   }//GEN-LAST:event_btnCategoryThreeActionPerformed

   private void btnCatOneReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatOneReviewActionPerformed

      // TODO add your handling code here:
      CardLayout cl = (CardLayout)(this.catOneCardPanel.getLayout());
      cl.show(this.catOneCardPanel, "Review");       
   }//GEN-LAST:event_btnCatOneReviewActionPerformed

   private void btnCatOneUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatOneUpdateActionPerformed
      // TODO add your handling code here:
      CardLayout cl = (CardLayout)(this.catOneCardPanel.getLayout());
      cl.show(this.catOneCardPanel, "Update"); 
   }//GEN-LAST:event_btnCatOneUpdateActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(TopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(TopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(TopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(TopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new TopFrame().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnCatOneReview;
   private javax.swing.JButton btnCatOneUpdate;
   private javax.swing.JButton btnCatOneView;
   private javax.swing.JButton btnCategoryOne;
   private javax.swing.JButton btnCategoryThree;
   private javax.swing.JButton btnCategoryTwo;
   private javax.swing.JPanel cardPanel;
   private javax.swing.JPanel catBlankPanel;
   private javax.swing.JPanel catFourPanel;
   private javax.swing.JPanel catOneBlankPanel;
   private javax.swing.JPanel catOneButtonPanel;
   private javax.swing.JPanel catOneCardPanel;
   private javax.swing.JPanel catOneCardPanelReview;
   private javax.swing.JPanel catOneCardPanelUpdate;
   private javax.swing.JPanel catOneCardPanelView;
   private javax.swing.JPanel catOnePanel;
   private javax.swing.JPanel catThreePanel;
   private javax.swing.JPanel catTwoPanel;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel lblCatOnePanel;
   private javax.swing.JLabel lblStart;
   private javax.swing.JPanel pnlCategoriesButtons;
   // End of variables declaration//GEN-END:variables
}
